A python code for implementing an **MLP ANN** using sklearn is given below.

In [ ]:
# Implementing MLP using sklearn
#The first step is to import the necessary modules for the implementation of an MLP ANN
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
np.random.seed(42)

#The data to be used for the implementation of the ANN algorithm is then loaded followed by splitting the dataset into the training and the test data.
mnist = load_digits()
X = mnist.data
Y = mnist.target
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

#The next step is to actually implement the MLP ANN algorithm:
clf = MLPClassifier(alpha=1, max_iter=1000)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

#the accuracy of the MLP ANN algorithm is explored, as shown in the following code snippet:
print('Accuracy is:', accuracy_score(y_test, y_pred))
print('\nClassification Report is:\n', classification_report(y_test, y_pred))
print('\nConfusion Matrix is:\n', confusion_matrix(y_test, y_pred))

Accuracy is: 0.9833333333333333

Classification Report is:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       0.97      1.00      0.98        28
           2       1.00      1.00      1.00        33
           3       1.00      0.97      0.99        34
           4       1.00      1.00      1.00        46
           5       0.94      0.98      0.96        47
           6       0.97      0.97      0.97        35
           7       1.00      0.97      0.99        34
           8       1.00      0.93      0.97        30
           9       0.98      1.00      0.99        40

    accuracy                           0.98       360
   macro avg       0.99      0.98      0.98       360
weighted avg       0.98      0.98      0.98       360


Confusion Matrix is:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0 

The python code for implementing an **SVM** using sklearn is given below.

In [ ]:
#implementing SVM using sklearn
#The first step in this code snippet is to import the necessary modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
np.random.seed(42)

#This is followed by loading the data that will be used for the SVM classification algorithm and splitting the data into training and test sets.
mnist = load_digits()
X = mnist.data
Y = mnist.target
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

#After splitting the data, the next step is to actually implement the SVM classifier
clf = SVC(kernel='rbf', gamma = 0.0001, C=1e1)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

#the last step is to explore the accuracy of the algorithm
print('Accuracy is:', accuracy_score(y_test, y_pred))
print('\nClassification Report is:\n', classification_report(y_test, y_pred))
print('\nConfusion Matrix is:\n', confusion_matrix(y_test, y_pred))

Accuracy is: 0.9861111111111112

Classification Report is:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00        28
           2       1.00      1.00      1.00        33
           3       1.00      0.97      0.99        34
           4       1.00      1.00      1.00        46
           5       0.96      0.98      0.97        47
           6       0.97      1.00      0.99        35
           7       0.97      0.97      0.97        34
           8       1.00      0.97      0.98        30
           9       0.97      0.97      0.97        40

    accuracy                           0.99       360
   macro avg       0.99      0.99      0.99       360
weighted avg       0.99      0.99      0.99       360


Confusion Matrix is:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0 

The python code for the implementation of **quantum SVM** is given below using qiskit. 

In [ ]:
#The first step involves importing the modules required for the implementation of the quantum SVM algorithm
!pip install qiskit
!pip install qiskit.aqua
#QSVM code 
#from qsvm_datasets import *
from qiskit import BasicAer
#from qsvm_datasets import qiskit_aqua
from qiskit.aqua import QuantumInstance, aqua_globals
from qiskit.aqua.algorithms import VQC, QSVM
from qiskit.aqua.components.multiclass_extensions import *
from qiskit.aqua.components.optimizers import COBYLA
from qiskit.aqua.components.feature_maps import RawFeatureVector
#from qiskit.aqua.algorithms.many_sample.qsvm._qsvm_estimator import _QSVM_Estimator
from qiskit.circuit.library import ZZFeatureMap, ZFeatureMap, PauliFeatureMap
from qiskit.ml.datasets import breast_cancer
from qiskit.circuit.library import TwoLocal
seed = 42
aqua_globals.random_seed = seed

#This is followed by the loading of the dataset and the preparation of data (pre-processing) for the implementation of the quantum SVM:
feature_dim = 4  # dimension of each data point
_, training_input, test_input, _ = breast_cancer(training_size=12,
                                        test_size=4,
                                        n=feature_dim)
feature_map = ZZFeatureMap(feature_dimension=feature_dim, reps=2, entanglement='linear')
#feature_map = RawFeatureVector(feature_dimension=feature_dim)
qsvm = QSVM(feature_map, training_input, test_input)

#The next step is to implement the quantum support vector algorithm and simulate this algorithm using 'qasm_simulator'
backend = BasicAer.get_backend('qasm_simulator')
quantum_instance = QuantumInstance(backend, shots=1024, seed_simulator=seed, seed_transpiler=seed)

result = qsvm.run(quantum_instance)


print('Testing accuracy: {:0.2f}'.format(result['testing_accuracy']))

     |████████████████████████████████| 2.1 MB 26.8 MB/s 
     |████████████████████████████████| 610 kB 46.7 MB/s 
     |████████████████████████████████| 6.4 MB 43.5 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
  Created wheel for dlx: filename=dlx-1.0.4-py3-none-any.whl size=5718 sha256=6c4bdb82fb5dd2453717d5a609ed55fbf365764c62135af69de9ce252006975d
  Stored in directory: /root/.cache/pip/wheels/78/55/c8/dc61e772445a566b7608a476d151e9dcaf4e092b01b0c4bc3c
  Created wheel for docplex: filename=docplex-2.23.222-py3-none-any.whl size=662847 sha256=a512fad3b2a9e3e4dc61aeafc22bfd168b5da0b55b22939fbb8de273d6c54024
  Stored in directory: /root/.cache/pip/wheels/a7/c9/fb/cee5a89f304e77a39c466e625ac2830434b76eb8384999d116
Successfully built dlx docplex
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: lxml
    Found existing installation: l

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: DeprecationWarning: The variable qiskit.aqua.aqua_globals is deprecated. It was moved/refactored to qiskit.utils.algorithm_globals (pip install qiskit-terra). For more information see <https://github.com/Qiskit/qiskit-aqua/blob/main/README.md#migration-guide>


Testing accuracy: 0.75


The python code for implementing the **quantum variational classifier** using qiskit is given below. 

In [ ]:
#The first step in the implementation of the quantum variational classifier is to import the necessary modules
!pip install qiskit
from qiskit import BasicAer
from qiskit.aqua import QuantumInstance, aqua_globals
from qiskit.aqua.algorithms import VQC
from qiskit.aqua.components.optimizers import COBYLA
from qiskit.circuit.library import ZZFeatureMap, ZFeatureMap, PauliFeatureMap
from qiskit.aqua.components.feature_maps import RawFeatureVector
from qiskit.ml.datasets import breast_cancer
from qiskit.circuit.library import TwoLocal
seed = 42
aqua_globals.random_seed = seed

#The next step is the preparation of data for the implementation of the quantum variational classifier algorithm
feature_dim = 4  # dimension of each data point
_, training_input, test_input, _ = breast_cancer(training_size=12,
                                        test_size=4,
                                        n=feature_dim)

#feature_map = ZZFeatureMap(feature_dimension=feature_dim, reps=2, entanglement='linear')
feature_map = RawFeatureVector(feature_dimension=feature_dim)
vqc = VQC(COBYLA(maxiter=1000),
          feature_map,
          TwoLocal(feature_map.num_qubits, ['ry', 'rz'], 'cz', reps=3),
          training_input,
          test_input)
#The quantum variational classifier is then simulated using the 'qasm_simulator':
backend = BasicAer.get_backend('qasm_simulator')
quantum_instance = QuantumInstance(backend, shots=1024, seed_simulator=seed, seed_transpiler=seed)

result = vqc.run(quantum_instance)

print('Testing accuracy: {:0.2f}'.format(result['testing_accuracy']))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: DeprecationWarning: The RawFeatureVector class has moved to qiskit.ml.circuit.library and subclasses the QuantumCircuit. This class, in qiskit.aqua.components, is deprecated as of Qiskit Aqua 0.9.0 and will be removed no earlier than 3 months after the release date.


Testing accuracy: 0.88
